spring.application.name=demo

# Esto es vital para que Hibernate cree las tablas en el contenedor
spring.jpa.hibernate.ddl-auto=create-drop
# Esto evita que Spring intente buscar una base de datos H2 embebida
spring.test.database.replace=none